apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-oxbsuzwp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/nodejs-oxbsuzwp:a0ca4f45026f8ca1477d033f927fbb576e5a8d9b@sha256:1b5d0b058fac93ce936b78323ce0d50c749545fe96696743b32ea227e13c7962
          name: container-image
